### ISSUE TITLE
Just wondering if the pretrained model will produce good results for non-English voice.

### ISSUE THREAD

**Issue by Michaelwhite34** [mindslab-ai/nuwave2#3]

**Comment by Seungwoo0326** [comment]
Hi! Thank you for the great question.

I checked whether NU-Wave 2 model can produce good results for Korean and here is an example of the KSS dataset (22050 Hz -> 48000 Hz).
I think the result is quite good.
It seems to work well because the audio super-resolution task does not depend on the language, unlike other tasks like TTS or STT.

I hope this helps!

![wav_l](https://user-images.githubusercontent.com/66414823/183243888-da5960f7-82b8-421d-b35b-98846c1052aa.png)
![result](https://user-images.githubusercontent.com/66414823/183243889-691419d7-3363-4915-8e12-616960fca8a9.png)
[result_kss.zip](https://github.com/mindslab-ai/nuwave2/files/9274785/result_kss.zip)
